#!/bin/bash

# Student Portal - Demo URLs
echo "🚀 Student Portal Demo URLs"
echo "================================"
echo ""
echo "📍 Main Routes:"
echo "Landing Page:     http://localhost:5173/"
echo "Login Page:       http://localhost:5173/login"
echo "Dashboard:        http://localhost:5173/dashboard"
echo ""
echo "📍 Dashboard Nested Routes:"
echo "Profile:          http://localhost:5173/dashboard/profile"
echo "Students List:    http://localhost:5173/dashboard/students"
echo ""
echo "📍 Dynamic Routes (Student Details):"
echo "Alice Johnson:    http://localhost:5173/dashboard/students/1"
echo "Bob Smith:        http://localhost:5173/dashboard/students/2"
echo "Charlie Brown:    http://localhost:5173/dashboard/students/3"
echo "Diana Prince:     http://localhost:5173/dashboard/students/4"
echo "Edward Davis:     http://localhost:5173/dashboard/students/5"
echo ""
echo "📍 Search Params (Course Filtering):"
echo "All Students:     http://localhost:5173/dashboard/students"
echo "Math Students:    http://localhost:5173/dashboard/students?course=math"
echo "Science Students: http://localhost:5173/dashboard/students?course=science"
echo "CS Students:      http://localhost:5173/dashboard/students?course=computer-science"
echo ""
echo "🔐 Authentication Notes:"
echo "- Login with any username to access dashboard"
echo "- Protected routes redirect to /login if not authenticated"
echo "- Use logout button to test authentication flow"
echo ""
echo "Server running at: http://localhost:5173/"
